### ISSUE TITLE
xml文件缺失

### ISSUE THREAD

**Issue by hongweipeng** [MashiMaroLjc/Learn-to-identify-similar-images#1]
程序中多次出现:`cvdata\\haarcascades\\haarcascade_frontalface_default.xml`，但找不到这个文件，实例图片也没传上来。

**Comment by MashiMaroLjc** [comment]
已经补回xml文件，多谢提醒。示例图片的问题可以随便找一个明星的图片来试一下就行。

**Comment by hongweipeng** [comment]
好的，收到，谢谢。
