### ISSUE TITLE
DCT变换中系数矩阵有误

### ISSUE THREAD

**Issue by hongweipeng** [MashiMaroLjc/Learn-to-identify-similar-images#2]
pHash.py的计算系数矩阵函数get_coefficient中
```
sqr = math.sqrt(1/n)
	value = []
	for i in range(0,n):
		value.append(sqr)
```
应为
```
sqr = math.sqrt(2.0 / n) * math.sqrt(1/n)
```

**Comment by MashiMaroLjc** [comment]
DCT算法是参考这篇[文章](http://blog.csdn.net/luoweifu/article/details/8214959)完成的

其中，其指出了系数矩阵为：

![系数矩阵](http://img.my.csdn.net/uploads/201211/23/1353633448_3354.png)

第一行把系数乘进去后，为```sqrt(2/N)*sqrt(1/2) = sqrt(1/N)```

**Comment by hongweipeng** [comment]
那没错，是我看错了，可耻的匿了
